apiVersion: 1

datasources:
  - name: benchmark_metrics
    uid: benchmark_metrics
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: benchmark_metrics
    isDefault: true
